name: Test GitHub Action
on: [pull_request, push]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master
      with: 
        files: ./*.md

    - name: Writes changes in the local checkout
      uses: crate-ci/typos@master
      with: 
        write_changes: true
